### ISSUE TITLE
ExtensionProvider: Do not support empty TransactionPayload for transaction data 

### ISSUE THREAD

**Issue by TheoSabattie** [ElrondNetwork/elrond-sdk-erdjs#110]
Hello',  

I'm trying to homogenize usage of all providers.
When I'm using ExtensionProvider:  
If I use sendTransaction without specifying data:
![image](https://user-images.githubusercontent.com/2721436/151937043-7e03b191-cbd3-4e9a-87a1-9cfefe1159ba.png)
(Not OK, I don't see any pending transaction)

If I use sendTransaction with `new TransactionPayload(" "):`
![image](https://user-images.githubusercontent.com/2721436/151936900-aec9c698-9068-4be7-9b8d-241b692398b8.png)
OK

Note: `new TransactionPayload("")`  does not work, data cannot be empty

I didn't find the extension repository so I report the inconsistant behaviour here. ;)

Thanks in advance! :)

Théo Sabattié

**Comment by andreigiura** [comment]
Hi @TheoSabattie, thanks for reporting this issue. We will have a look and close this issue after the fix.

**Comment by andreigiura** [comment]
Issue is fixed
