### ISSUE TITLE
SmartContractAbi.fromAbiPath no longer works in browser

### ISSUE THREAD

**Issue by raress96** [ElrondNetwork/elrond-sdk-erdjs#115]
In version 9, this check was added:
https://github.com/ElrondNetwork/elrond-sdk-erdjs/commit/18b80f30d75a770e8881dcd932aa0915084701b3#diff-a8543e5d2b9e39b484b691ba3c82d8e25c14e9e06a19874b5d2d3749773f96a6R42

Which no longer detects browsers correctly if not in tests. Please fix this so we can still use that function in browser context or provide an alternative.

For now I believe a polyfill to fs can be added in my project, but haven't tested fully and that should not be required.

**Comment by andreibancioiu** [comment]
Hello @raress96! 
Thank for reporting the issue (and for the investigation) :rocket: 

The old `isBrowser()` function was not originally intended to be used in production code (it has been defined in the `testutils` module).

We've opened the PR https://github.com/ElrondNetwork/elrond-sdk-erdjs/pull/121.

As a temporary workaround, until we release the fix on npmjs, please use the code within `fromAbiUrl()` to create your `SmartContractAbi`.
