### ISSUE TITLE
Missing devDependency `ledgerhq__hw-transport`

### ISSUE THREAD

**Issue by raress96** [ElrondNetwork/elrond-sdk-erdjs#116]
In vesrion 9 the following error appears in NodeJs context:
`node_modules/@elrondnetwork/erdjs/out/dapp/hwProvider.d.ts:2:39 - error TS2307: Cannot find module 'ledgerhq__hw-transport' or its corresponding type declarations.`

This is fixed by adding in devDependencies the following:
`"@types/ledgerhq__hw-transport": "^4.21.4"`

This should be included in the library IMO.

**Comment by andreibancioiu** [comment]
@raress96, thank you for reporting the issue.

Until we apply a proper fix, an alternative workaround (other than the one mentioned by you) would be to set the following in your `tsconfig.json`:

```
{
    "compilerOptions": {
        ...
        "skipLibCheck": true,
        ...
    },
    ...
}
```

**Comment by andreibancioiu** [comment]
As of erdjs 10 (we are currently preparing the release), the hardware wallet (Ledger) integration package has been extracted to:

 - https://github.com/ElrondNetwork/elrond-sdk-erdjs-hw-provider
