### ISSUE TITLE
Transactions signed Web Wallet + Ledger fail on sending

### ISSUE THREAD

**Issue by paul-v-87** [ElrondNetwork/elrond-sdk-erdjs#135]
When signing transactions via the Web Wallet provider, where the user logs in their wallet via Ledger, transactions come back signed without any issue, but when trying to send them via the ProxyProvider I receive the following error:

```
transaction generation failed: ed25519: invalid signature
```

After a brief discussion with @StanislavSava, he suggested I open this issue for the Elrond team to pick up from here. I'm not excluding we might be doing something wrong, but I'm looking for some directions.

Just to clarify, we are talking about WalletProvider which is logged in using Ledger, we are not using HwProvider directly.

**Comment by andreibancioiu** [comment]
@paul-v-87, do you think you can provide us a code snippet that you use to build & sign the transaction? Is the issue reproducible?

**Comment by FrenchW** [comment]
Issue confirmed here

**Comment by paul-v-87** [comment]
> @paul-v-87, do you think you can provide us a code snippet that you use to build & sign the transaction? Is the issue reproducible?

I'll put together a minimum reproduction example and get back to you.

For the time being, you can test this with a Ledger device on https://lockedmex.exchange. If you try to swap a small amount of EGLD to LKMEX via Web Wallet + Ledger, you can then inspect the transaction being sent to the gateway API. The request always fails with the error I mentioned in the issue description.

**Comment by paul-v-87** [comment]
> sign the transaction

Just to clarify: the signature is handled entirely by the Web Wallet, I'm only building the transaction, forwarding it to Web Wallet and then sending the signed transaction to the gateway API.

**Comment by andreibancioiu** [comment]
@paul-v-87, thank you for the notes :pray: 

Can you confirm whether you use an address index different than 0 on the Ledger device?

**Comment by paul-v-87** [comment]
I always used the first address, I assume that one has index 0, right? I never tried any of the other addresses on the Ledger, as they don't have any funds on them.

**Comment by paul-v-87** [comment]
For further context, all of our users using a Ledger device on the Web Wallet receive this error, so the signing always fails in this particular scenario.

**Comment by paul-v-87** [comment]
Here is a minimum reproduction example of how we login, build transactions, send them for signing and finally submit them to the network: https://gist.github.com/paul-v-87/d1052ed5c1e33be7203cbf779ac4fcf2

It needs to be run in an environment where the `erdjs` modules are ready to be imported. You just need to run `main()` every time the page is entered, and it'll handle everything.

**Comment by paul-v-87** [comment]
Hello! Is there any update on this issue?

Can I do anything to help? I can try to patch up the issue if it's in `erdjs` and you give me some tips on where to start.

Implementing the full Ledger flow in our own stack is a bit prohibitive due to complexity and time constraints, so we have to rely on the Web Wallet as a gateway for our Ledger users.

**Comment by andreibancioiu** [comment]
@paul-v-87, sorry for the delay. Will start working on this as of this moment :pray:

**Comment by andreibancioiu** [comment]
@paul-v-87, thank you very much for the script! I've reproduced the issue.

Given a simple transaction:
```
const transaction = new Transaction({
  receiver: new Address('erd1qyu5wthldzr8wx5c9ucg8kjagg0jfs53s8nr3zpz3hypefsdd8ssycr6th'),
  value: Balance.egld(0.001),
  gasLimit: new GasLimit(100000),
  data: new TransactionPayload("test")
});
```

The transaction JSON, as obtained from the Wallet Provider using Ledger, is as follows:

```
{
    "nonce": 67,
    "value": "1000000000000000",
    "receiver": "erd1qyu5wthldzr8wx5c9ucg8kjagg0jfs53s8nr3zpz3hypefsdd8ssycr6th",
    "sender": "erd1qyu5wthldzr8wx5c9ucg8kjagg0jfs53s8nr3zpz3hypefsdd8ssycr6th",
    "gasPrice": 1000000000,
    "gasLimit": 100000,
    "data": "dGVzdA==",
    "chainID": "T",
    "version": 2,
    "signature": "52db2492821d0788e6f625fbe0aec02955447c801f1eabcb8d7a6d119b2a7338eab7a49e9c5b6c7cb659a5d4e6df4b8dc49f279f7e41dec16d7149758a5ebc03"
}
```

The transaction JSON, as obtained from erdpy is as follows:

```
erdpy tx new --chain=T --nonce=67 --receiver=erd1qyu5wthldzr8wx5c9ucg8kjagg0jfs53s8nr3zpz3hypefsdd8ssycr6th --ledger --gas-limit=100000 --data=test --value=1000000000000000
```

```
{
   "nonce": 67,
    "value": "1000000000000000",
    "receiver": "erd1qyu5wthldzr8wx5c9ucg8kjagg0jfs53s8nr3zpz3hypefsdd8ssycr6th",
    "sender": "erd1qyu5wthldzr8wx5c9ucg8kjagg0jfs53s8nr3zpz3hypefsdd8ssycr6th",
    "gasPrice": 1000000000,
    "gasLimit": 100000,
    "data": "dGVzdA==",
    "chainID": "T",
    "version": 2,
    "options": 1,
    "signature": "52db2492821d0788e6f625fbe0aec02955447c801f1eabcb8d7a6d119b2a7338eab7a49e9c5b6c7cb659a5d4e6df4b8dc49f279f7e41dec16d7149758a5ebc03"
}
```

Note, the signatures are the same, but the first one is missing the `options` field. The first transaction fails (invalid signature), while the one from erdpy succeeds.

The fix should theoretically be applied in `src/dapp/walletProvider.ts`. We will come back once it's ready and tested.

Until the next release (most probably on Friday or Monday), you can apply the following temporary workaround in your code:

```
function sendTransaction(proxyProvider: any, signedTransaction: any) {
    if (signedTransaction.version.valueOf() == 2) {
        signedTransaction.options = new TransactionOptions(1);
    }

    signedTransaction.send(proxyProvider);
}
```

Here's the sent transaction (on testnet, from the `Alice` wallet): https://testnet-explorer.elrond.com/transactions/8f2d849a516ec464581612b4d93f0ff395db448c32e465a33b2d612a1f1cc570

Again, many thanks for the detailed input :pray:

**Comment by andreibancioiu** [comment]
@paul-v-87, the fix will be release soon.

Just an extra note - instead of using URL manipulation (a bit fragile):
```
const newUrl = `${window.location.href}&chainID[0]=${chainID}&version[0]=${version}`;
window.history.replaceState({ path: newUrl }, '', newUrl);
```

... you can use `walletProvider.signTransactions` (the plural form), and set the `chainID` and `version` on the transaction object itself, in advance. For mainnet, set `tx.chainID = new ChainID("1")` and `tx.version = new TransactionVersion(1)`. The version field will actually be overridden when signing with ledger. 

The function `walletProvider.signTransaction` (the singular form) has a small inconvenience of not passing the fields `chainID` and `version` to the web wallet.

**Comment by andreibancioiu** [comment]
Fixed in v9.2.2 :pray:

**Comment by paul-v-87** [comment]
Thank you, this is much appreciated! 🙏  I'm currently stuck on another bug after upgrading (most likely something wrong in our own code), but as soon as I can test this properly I'll provide some feedback.

Also thanks for the suggestion with the chain ID and version improvements - I agree the current solution is fragile, I simply didn't know how else to fix it.

**Comment by paul-v-87** [comment]
This works as expected now, thank you for the help!
