### ISSUE TITLE
Publish `@elrondnetwork/hw-app-elrond` on Github

### ISSUE THREAD

**Issue by lcswillems** [ElrondNetwork/elrond-sdk-erdjs#204]
Hi!

`@elrondnetwork/elrond-sdk-erdjs-hw-provider` depends on `@elrondnetwork/hw-app-elrond`.

I would like to create a pull request for this package in order to remove its dependency on `node-hid`.

Would it be possible to publish `@elrondnetwork/hw-app-elrond` on Github?

**Comment by andreibancioiu** [comment]
Hello @lcswillems and thank you for the reminder :pray: 

The repository is now public:

https://github.com/ElrondNetwork/hw-app-elrond

**Comment by lcswillems** [comment]
Thanks a lot!

**Comment by lcswillems** [comment]
I have just created the PR: https://github.com/ElrondNetwork/hw-app-elrond/pull/11/files
