### ISSUE TITLE
MapMapper/SetMapper ABI deserialization

### ISSUE THREAD

**Issue by cucunber** [ElrondNetwork/elrond-sdk-erdjs#211]
Hi, try to write ABI for smart contract. One of the views looks like this:
```Rust
#[view]
#[storage_mapper("allowed_tokens_set")]
    fn allowed_tokens_set(&self) -> SetMapper<TokenIdentifier>;
```
As you can see it returns **SetMapper** (my knowledge in Rust is poor), as I understand it is a simple **List**

When i get info from this method raw data consists of array which contains 3 elements,  but after deserialization i get first element from this array and nothing more

ABI:
```JavaScript
const ABI = {
  name: 'crowdsale',
  constructor: {
    inputs: [],
    outputs: [],
  },
  endpoints: [
    {
      name: 'start_timestamp',
      inputs: [],
      outputs: [
        {
          type: 'u64',
        },
      ],
    },
    {
      name: 'allowed_tokens_set',
      inputs: [],
      outputs: [
        {
          type: 'List<TokenIdentifier>',
        },
      ],
    },
    {
      name: 'allowed_tokens_map',
      inputs: [],
      outputs: [
        {
          type: 'tuple2<TokenIdentifier, u8>',
        },
      ],
    },
  ],
}
```

Getting data:
``` TypeScript
const method = 'allowed_tokens_set';
const myAddress = new Address(elraddress);
const contractAddress = new Address(contracts.crowdSale.address);
const contractAbi = new SmartContractAbi(contracts.crowdSale.abi, ['crowdsale']);
const contract = new SmartContract({ address: contractAddress, abi: contractAbi });

const query = contract.createQuery({
    func: new ContractFunction(method),
    args: [],
    caller: myAddress,
 });

 const proxyProvider = new ProxyNetworkProvider('https://testnet-gateway.elrond.com');
 const queryResponse = await proxyProvider.queryContract(query);
 const resultsParser = new ResultsParser();
 const endpointDefinition = contract.getEndpoint(method);
 const bundle = resultsParser.parseQueryResponse(queryResponse, endpointDefinition);
 console.log(bundle.values, queryResponse);
```

In which place i've done something wrong?(

**Comment by andreibancioiu** [comment]
Hello @cucunber!

Theoretically, `values` contains **a single object** in your case, which is, actually, **a list** of token identifiers (according to the ABI).

Therefore, you can do as follows:

```
console.log(bundle.values[0].valueOf());
```

Or:

```
const { firstValue } = resultsParser.parseQueryResponse(queryResponse, endpointDefinition);
console.log(firstValue.valueOf());
```

Does this solve the issue?

**Comment by cucunber** [comment]
@andreibancioiu 
thanks for your response, but **List** which is consist in `values` field contains only one token identifier, but serialized response contain 3 base64 strings
serialized response:
![image](https://user-images.githubusercontent.com/61382836/167388786-5c5a17b6-2829-4e37-8da0-55fe5a64dc2b.png)

deserialized object:
![image](https://user-images.githubusercontent.com/61382836/167388962-79ce71ee-0dd0-45a0-aa90-e3d0f74a2d1f.png)

if i decode serialized values it will be 3 different tokens

**Comment by claudiu725** [comment]
@cucunber 
Hi. There was a bug in older versions (versions <0.28 - relevant PR with the fix https://github.com/ElrondNetwork/elrond-wasm-rs/pull/588) of the elrond-wasm-rs framework where the ABI for SetMapper incorrectly reports `List<T>` when it should actually be `variadic<T>`. Could you upgrade to a more recent version and re-build the ABI and then try again?
The latest elrond-wasm-rs version at the moment is 0.31.1

**Comment by cucunber** [comment]
@claudiu725 thanks so much, this helps me
