### ISSUE TITLE
Custom signin process / Sign in transaction with ibm hyper protect crypto services using the enterprise pkcs11(ep11)

### ISSUE THREAD

**Issue by dimitardanailov** [ElrondNetwork/elrond-sdk-erdjs#215]
Greetings, 

I've been working as an engineer for https://propine.com. Our solution uses ibm hyper protect crypto services using the enterprise pkcs11(ep11) to sign transactions or create a new address. 

Unfortunately: 
My team has an issue with the following error:
[Error]: Request error on url [transaction/send]: [transaction generation failed: ed25519: invalid signature]

The hex is valid. As a validator: We're using: https://github.com/ElrondNetwork/elrond-sdk-erdjs/blob/main/src/signature.ts#L39

Source code snippet:
```javascript
const signingMessage = rawTx
      .serializeForSigning(rawTx.getSender())
      .toString("hex");
      
// Custom ibm hyper protect crypto services using the enterprise pkcs11(ep11) signature generation
const { signature } = await sign();
const elrondSignature = Signature.toBuf(signature);
const signs = new ElrondSignature(elrondSignature);

rawTx.applySignature(signs, senderAddress);
const txHash = await this.proxyProvider.sendTransaction(rawTx);
const transactionWatcher = new TransactionWatcher(this.proxyProvider);
await transactionWatcher.awaitCompleted(rawTx);
 ```

**Comment by AdoAdoAdo** [comment]
can you check differences between your generated signature and the one provided by the signer in erdjs? 
I suspect your sign() generates something different

**Comment by dimitardanailov** [comment]
Greetings, 

The signature format is: 

```json
signature {
  r: '414c45418bb5e7485b6696539ef2efc114093be94b8286f80c0f9c38b9c37759',
  s: 'b4f05cf6a427c1a573c0508ca9d8cc28b7f8bd32bc137d7817bccc4506dd720f'
}
```

as a algorithm is: ED25519. So far we completed the integration for Algorand, Cardano, Casper, Solana. The signature algorithm for these protocols is the same like: Elrond -> ED25519.

**Comment by ccorcoveanu** [comment]
Hello!

Is the code snippet incomplete? I am curious what the `sign` function does, since it does not have any params in this example. Does it transform the input (or the `signingMessage`) in any way? Or it just purely signing that Buffer?

**Comment by dimitardanailov** [comment]
Greetings, 

I'd like to share the whole function: 

```javascript
const signingMessage = rawTx
      .serializeForSigning(rawTx.getSender())
      .toString("hex");
     
 const message = { signingMessage };

 const { signature } = await sign(
    keystoreId,
    transactionId,
    signingMessage,
    SigningAlgorithm.ED25519,
    isColdWalletRequest
); 
```

**Comment by ccorcoveanu** [comment]
Hi again, I was interested in the internals of `sign`. Is a function you guys wrote or a library? Can you provide a link for it?
It could be that it signs the hash, or something. Or maybe does not use clamping (although that would have been an issue for other chains also).

`ElrondSignature` is just an implementation for `ISignature` and just concatenates `r` and `s` right?

**Comment by ccorcoveanu** [comment]
Also, you are converting the signable buffer to a hex string. Note that the signature should be over the actual buffer, not over that string

**Comment by dimitardanailov** [comment]
@ccorcoveanu 

We've a private library. The package has a mission to interact with: https://www.ibm.com/cloud/hyper-protect-crypto. I'm a group leader in the company. I don't have so much experience with Elrond. My colleague did a trivial mistake. He used incorrect configurations and this is the reason the signature to be invalid. We fixed our configurations. We've several successful transactions:
https://testnet-explorer.elrond.com/accounts/erd1e5ss7lus4936samrp3pzagewl4m06sgvzthu4fegjf2e8slfmans7dnlgc

My plan is to close the ticket. If you want to understand more about our solution please ping (email, discord or telegram).
