### ISSUE TITLE
axios.defaults.transformResponse setting causes arweave (and other string only axios) to fail

### ISSUE THREAD

**Issue by pctj101** [ElrondNetwork/elrond-sdk-erdjs#46]
Erdjs introduces a changes in 2 files to axios which causes arweave-js to fail

https://github.com/ElrondNetwork/elrond-sdk-erdjs/blob/main/src/apiProvider.ts#L94
https://github.com/ElrondNetwork/elrond-sdk-erdjs/blob/main/src/proxyProvider.ts#L184
```
// See: https://github.com/axios/axios/issues/983
axios.defaults.transformResponse = [
  function(data) {
    return JSONbig.parse(data);
  },
];
```

An example of where this causes problems is if another npm package wants to fetch a pure string from another endpoint, even with content type text/html, JSONbig.parse(data) fails to parse a string which is invalid JSON.

As documented here, it takes a slightly strange work-around to deal with this
https://github.com/ArweaveTeam/arweave-js/pull/97

Would it be better to include this tranformResponse configuration along with each axios request to avoid disturbing other npm packages?

**Comment by ccorcoveanu** [comment]
Good catch, not the best choice to make global changes to imported libraries. Will review your PR and definitely change this approach
