### ISSUE TITLE
Angular 12 (webpack 5) and erdjs throws errors

### ISSUE THREAD

**Issue by mrazvanalex** [ElrondNetwork/elrond-sdk-erdjs#79]
**How to reproduce:** 

1. Create a fresh Angular 12 project `ng new` after installing the global cli for Angular `npm install -g @angular/cli`
2. Install erdjs `npm i @elrondnetwork/erdjs`
3. Pop in the first lines of code from erdjs docs `let provider = new ProxyProvider("https://localhost:7950");` in the home component and start the dev server using `ng serve` 

You will get the following errors:
![image](https://user-images.githubusercontent.com/6265028/136692832-0b5c099f-98fe-4edf-8ef7-3f595d3f2c1e.png)

Went over and installed
```
"browserify": "^17.0.0",
"crypto-browserify": "^3.12.0",
"https-browserify": "^1.0.0",
"path-browserify": "^1.0.1",
"stream-browserify": "^3.0.0",
```

Then added them as paths in **tsconfig.json**

```
"compilerOptions":{
    "paths": {
      "crypto": ["./node_modules/crypto-browserify"],
      "stream": ["./node_modules/stream-browserify"],
      "path": ["./node_modules/path-browserify"],
    }
}
```

Great, the webpack errors are gone. We're left with the filesystem (fs). After some research, I decided that a "browserify" version of fs might also fix the problem. So went over and installed browserify-fs `npm i browserify-fs` and also added in the above compilerOptions -> paths object. Now it looks like this:
```
"compilerOptions":{
    "paths": {
      "crypto": ["./node_modules/crypto-browserify"],
      "stream": ["./node_modules/stream-browserify"],
      "path": ["./node_modules/path-browserify"],
      "fs": ["./node_modules/browserify-fs"]
    }
}
```

Go ahead and restart the dev server with `ng serve`. Now the compiler doesn't throw any more errors, but a quick look at the actual app and we will notice that things are not fixed.
We notice that "process" is undefined in the Chrome Developer Console
![image](https://user-images.githubusercontent.com/6265028/136693098-fa15b310-bd4f-42fa-b34a-923b200184b4.png)

Went over to polyfills.ts and added these lines: 
```(window as any).global = window;
import { Buffer } from 'buffer';
global.Buffer = Buffer;
global.process = {
   env: { DEBUG: undefined },
   version: '',
   } as any;
```
I skipped a few steps because only adding global.process would then throw the undefined Buffer error, so I just added Buffer aswell along with global.

We are now left with the error "__dirname is not defined"
![image](https://user-images.githubusercontent.com/6265028/136693169-6bbb43d5-90f8-47bd-87cf-7ce42328ce9d.png)

which I am clueless of how to fix and already think that all the workarounds might eventually just create a waterfall crash. 

**Conclusions:**

This last bit seems to be a duplicate of : https://github.com/ElrondNetwork/elrond-sdk-erdjs/issues/77 but I feel like the whole road to get to the error described here is also quite cumbersome as you just fix error after error only to be faced with another one.

Is there a compatibility missmatch? Is the erdjs package only meant to be used on NodeJS and not in the browser? Or is it just a problem because of the new Webpack version and we're just missing the real fix?

**Comment by MWFIAE** [comment]
Ok I have reproduced the error and it seems like __dirname is used in the following files:

https://github.com/ElrondNetwork/elrond-sdk-erdjs/blob/main/src/smartcontracts/wrapper/systemWrapper.ts#L11

https://github.com/ElrondNetwork/elrond-sdk-erdjs/blob/main/src/testutils/wallets.ts#L49

According to nodejs.org its a difference between es modules and commonjs modules.
https://nodejs.org/api/esm.html#esm_differences_between_es_modules_and_commonjs

![image](https://user-images.githubusercontent.com/6072971/136695530-ef6b997f-2172-4756-bbe9-e3df8d8208a2.png)


One can also take a look at the issue here:
https://github.com/nodejs/help/issues/2907

So as far as I understood it we should replace all occurences of __dirname with smth like this:
https://github.com/nodejs/help/issues/2907#issuecomment-757446568

**Comment by mrazvanalex** [comment]
Have you done any other changes? I tried this fix and I get 
```
/node_modules/@elrondnetwork/erdjs/out/smartcontracts/wrapper/systemWrapper.js:4:18-31 - Error: export 'fileURLToPath' (imported as 'fileURLToPath') was not found in 'url' (possible exports: Url, format, parse, resolve, resolveObject)

./node_modules/@elrondnetwork/erdjs/out/testutils/wallets.js:4:19-32 - Error: export 'fileURLToPath' (imported as 'fileURLToPath') was not found in 'url' (possible exports: Url, format, parse, resolve, resolveObject)

```

The thing is.... 
![image](https://user-images.githubusercontent.com/6265028/136696385-952df52e-be9d-48fd-b14d-eba946607d3b.png)
the exported method si right there, I don't understand how it was not found. Tried to rebuild and all and still getting this.

Did it just "work" for you out of the box after making the changes?

**Comment by keyur555** [comment]
> Hi, i have setup a git repository with a workaround for using erdjs with angular. https://github.com/andreigiura/angular-erdjs-project , it is not pretty, since i have compiled the browser version of erdjs and paste it in the project, but it work for now, until we will figure it out.

Have you guys made any progress on figuring this out?
