### ISSUE TITLE
axios dependency vulnerability

### ISSUE THREAD

**Issue by juliancwirko** [ElrondNetwork/elrond-sdk-erdjs#89]
hi, npm audit complains about axios vulnerability with high severity status, could we update it? 
I am not sure from which branch the lib is published in the npm registry.

https://github.com/advisories/GHSA-cph5-m8f7-6c5x

**Comment by apopiidoru** [comment]
Fixed in https://github.com/ElrondNetwork/elrond-sdk-erdjs/pull/99/commits
